#!/bin/bash
# ECTC Project Summary and Quick Start
# This script provides an overview of the ECTC project

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  ECTC: Energy-Communication-Computation Coupled Optimization  ║"
echo "║           Complete Project Implementation v1.0                 ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "PROJECT STRUCTURE:"
echo "=================="
echo ""
echo "firmware/                 - MCU firmware (CC2650)"
echo "├── ectc_node/            │   - Core control loop"
echo "│   ├── Core/             │   - ECTC main, Shapley local, Lyapunov"
echo "│   ├── ML/               │   - TinyLSTM quantized inference"
echo "│   ├── ZKP/              │   - Pedersen commitments"
echo "│   ├── trace/            │   - Event tracer (200B buffer)"
echo "│   ├── Drivers/          │   - BQ25570, Radio drivers"
echo "│   └── include/          │   - Header files"
echo "├── build.sh              - Build script"
echo "└── linker.ld             - Memory layout (40KB SRAM, 128KB Flash)"
echo ""
echo "gateway/                  - Gateway services (Python)"
echo "├── ectc_gateway/         │   - Core services"
echo "│   ├── core/             │   - Shapley server, KF-GP hybrid"
echo "│   ├── models/           │   - TinyLSTM & KF-GP parameters"
echo "│   └── utils/            │   - Utility functions"
echo "├── requirements.txt      - Python dependencies"
echo "└── setup.py              - Package setup"
echo ""
echo "simulation/               - Large-scale simulator"
echo "├── simulator.py          - 1000+ node cycle-accurate simulator"
echo "├── spice_netlists/       - SPICE energy models"
echo "└── rtl_power_models/     - RTL power estimation"
echo ""
echo "evaluation/               - Testing and benchmarks"
echo "├── scripts/              │   - Evaluation framework"
echo "├── traces/               │   - 30-day energy traces"
echo "├── baselines/            │   - BATDMA, Mementos, etc."
echo "└── results/              │   - Test results"
echo ""
echo "tools/                    - Development tools"
echo "├── train_tinylstm.py     - Model training & quantization"
echo "├── energy_profiler.py    - Hybrid RTL+SPICE energy profiler"
echo "└── co_profiler.py        - Co-design profiler"
echo ""
echo "docs/                     - Documentation"
echo "├── architecture.md       - System architecture"
echo "├── hardware_setup.md     - Hardware assembly guide"
echo "├── software_deployment.md - Deployment instructions"
echo "└── api_reference.md      - REST API documentation"
echo ""
echo "scripts/                  - Automation"
echo "├── install.sh            - Environment setup"
echo "├── build.sh              - Build all components"
echo "└── deploy.sh             - Deploy to testbed"
echo ""
echo "QUICK START:"
echo "============"
echo ""
echo "1. Install dependencies:"
echo "   ./scripts/install.sh"
echo ""
echo "2. Build everything:"
echo "   ./scripts/build.sh"
echo ""
echo "3. Deploy to testbed:"
echo "   ./scripts/deploy.sh --num-nodes 5"
echo ""
echo "4. Run evaluation:"
echo "   python evaluation/scripts/evaluator.py"
echo ""
echo "KEY FEATURES:"
echo "============="
echo ""
echo "✓ Truncated Lyapunov Game"
echo "  - Prevents energy overflow with quartic penalty"
echo "  - Bounded energy queues"
echo ""
echo "✓ Stratified Shapley Values"
echo "  - O(N log(1/δ)/ε²) complexity"
echo "  - Spatial stratification"
echo ""
echo "✓ TinyLSTM Energy Predictor"
echo "  - Int8 quantized weights"
echo "  - 2-bit activation (ternary)"
echo "  - <4KB memory footprint"
echo "  - ~23μJ inference energy"
echo ""
echo "✓ KF-GP Hybrid Data Recovery"
echo "  - Temporal (Kalman) + Spatial (GP)"
echo "  - Automatic Cauchy kernel switching"
echo "  - Robust under energy scarcity"
echo ""
echo "✓ Pedersen Commitments (ZK Proof)"
echo "  - Secure energy state reporting"
echo "  - Hiding + Binding properties"
echo "  - Zero-knowledge verification"
echo ""
echo "PERFORMANCE (Paper Results):"
echo "============================"
echo ""
echo "Framework      | Data Integrity | Energy Cost | Sleep | P95 Latency"
echo "---------------|----------------|-------------|-------|-------------"
echo "ECTC           |      93.2%     |   45.7 nJ   | 87.3% |    1.83s   "
echo "BATDMA         |      78.4%     |   62.3 nJ   | 72.1% |    3.21s   "
echo "Mementos       |      71.2%     |   78.9 nJ   | 65.8% |    4.56s   "
echo "Alpaca         |      68.9%     |   84.2 nJ   | 61.2% |    5.34s   "
echo ""
echo "HARDWARE REQUIREMENTS:"
echo "======================"
echo ""
echo "Minimum Testbed (5 nodes):"
echo "  - 5x TI CC2650STK SensorTags    $125"
echo "  - 5x BQ25570EVM-206             $500"
echo "  - 5x 100μF capacitors             $5"
echo "  - Raspberry Pi 4B                 $75"
echo "  - 1x CC1352P1 LaunchPad          $30"
echo "  - Monsoon HV Power Monitor    $1,500"
echo "  ----------------------------------------"
echo "  TOTAL:                         $2,235"
echo ""
echo "HARDWARE MODIFICATIONS:"
echo "======================="
echo ""
echo "1. Remove CR2032 battery from CC2650STK"
echo "2. Connect BQ25570 to solar panel (2.4V MPPT)"
echo "3. Add 100μF capacitor between VSTOR and GND"
echo "4. Add voltage divider for ADC monitoring"
echo "5. Wire VSTOR to CC2650 VDD pin"
echo ""
echo "SOFTWARE COMPONENTS:"
echo "===================="
echo ""
echo "MCU Firmware (C):"
echo "  ✓ ECTC main control loop (100ms slots)"
echo "  ✓ TinyLSTM inference engine (quantized)"
echo "  ✓ Local Shapley calculator (O(1))"
echo "  ✓ Pedersen commitment engine"
echo "  ✓ Event tracer (200-byte buffer)"
echo "  ✓ BQ25570 driver"
echo "  ✓ IEEE 802.15.4 radio stack"
echo ""
echo "Gateway (Python):"
echo "  ✓ Stratified Shapley server"
echo "  ✓ KF-GP hybrid data recovery"
echo "  ✓ ZK proof verifier"
echo "  ✓ Particle filter for mobile nodes"
echo "  ✓ REST API (port 8080)"
echo "  ✓ WebSocket real-time updates"
echo ""
echo "Simulation:"
echo "  ✓ Cycle-accurate network simulator"
echo "  ✓ Energy harvesting models"
echo "  ✓ Mobile node mobility"
echo "  ✓ Event-driven simulation"
echo "  ✓ Parallel computation support"
echo ""
echo "EVALUATION:"
echo "==========="
echo ""
echo "✓ Reproduces paper Table 1 results"
echo "✓ Ablation study framework"
echo "✓ Dynamic response analysis (Fig 6)"
echo "✓ Baseline comparisons (5 frameworks)"
echo "✓ Automated testing suite"
echo ""
echo "ALGORITHM DETAILS:"
echo "=================="
echo ""
echo "1. Truncated Lyapunov:"
echo "   L(Q_E) = 0.5*ΣQ², Q≤0.9*C_cap"
echo "   L(Q_E) = 0.5*(0.9*C)² + β*(Q-0.9*C)⁴, Q>0.9*C_cap"
echo ""
echo "2. Stratified Shapley:"
echo "   Sample count: mk = |Ck|/N * log(1/δ) / ε²"
echo "   Complexity: O(N log(1/δ) / ε²)"
echo ""
echo "3. TinyLSTM:"
echo "   Architecture: Input(10) → LSTM(32) → Output(1)"
echo "   Quantization: Int8 weights, 2-bit activations"
echo "   Memory: <4KB, Energy: ~23μJ per inference"
echo ""
echo "4. KF-GP Hybrid:"
echo "   KF: Temporal dynamics (x_t = x_{t-1} + v_t)"
echo "   GP: Spatial correlation (RBF/Cauchy kernel)"
echo "   Switching: Cauchy when <30% nodes have low energy"
echo ""
echo "5. Pedersen Commitment:"
echo "   C = g^x * h^r (secp256k1 curve)"
echo "   Hiding: Energy value hidden"
echo "   Binding: Cannot change after commit"
echo ""
echo "DEPLOYMENT OPTIONS:"
echo "==================="
echo ""
echo "1. Docker (Recommended):"
echo "   docker build -f Dockerfile.gateway -t ectc-gateway ."
echo "   docker run -p 8080:8080 ectc-gateway"
echo ""
echo "2. Raspberry Pi:"
echo "   ./scripts/install.sh"
echo "   ./scripts/deploy.sh --gateway raspberry-pi"
echo ""
echo "3. Development:"
echo "   cd gateway && python -m ectc_gateway.main"
echo ""
echo "TESTING:"
echo "========"
echo ""
echo "Unit Tests:"
echo "  pytest tests/ -v"
echo ""
echo "Integration Tests:"
echo "  ./scripts/run_testbed.sh --num-nodes 5"
echo ""
echo "Performance Evaluation:"
echo "  python evaluation/scripts/evaluator.py"
echo ""
echo "Energy Profiling:"
echo "  python tools/energy_profiler.py"
echo ""
echo "DOCUMENTATION:"
echo "=============="
echo ""
echo "Full documentation available in docs/ directory:"
echo "  - System Architecture (docs/architecture.md)"
echo "  - Hardware Setup (docs/hardware_setup.md)"
echo "  - Software Deployment (docs/software_deployment.md)"
echo "  - API Reference (docs/api_reference.md)"
echo ""
echo "SUPPORT:"
echo "========"
echo ""
echo "GitHub Issues: https://github.com/ectc/ectc-project/issues"
echo "Documentation: https://ectc.readthedocs.io"
echo "Email: support@ectc-project.org"
echo ""
echo "CITATION:"
echo "========="
echo ""
echo "@inproceedings{zhang2024ectc,"
echo "  title={ECTC: A Game-Theoretic Framework for Energy-Communication-Computation}"
echo "         Coupled Optimization in Battery-Free Sensor Networks},"
echo "  author={Zhang, Chong and Wang, Binxu and Chen, Yifei and Li, Ming},"
echo "  booktitle={IEEE International Conference on RTCSA},"
echo "  year={2024}"
echo "}"
echo ""
echo "LICENSE: Apache 2.0"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                   ECTC Project Ready!                          ║"
echo "║        Run ./scripts/install.sh to get started                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
